### ISSUE TITLE
5:1 Ratio?

### ISSUE THREAD

**Issue by opello** [cazzar/SteamSummerMinigameAutoBuy#1]
It seems like the latest in the MSG2015 group is to have a 5:1 ratio, so this should probably be updated (although I don't know how many people are using it).

**Comment by opello** [comment]
I think that might have been premature, latest strategy that I see now is saying 10:1 still.  Probably disregard.

**Comment by Cazzar** [comment]
Since it is offically being put out there for record attempts, 142976b1d implements this. (I think)
